---
- import_tasks: packages.yml
  tags: packages
- import_tasks: slack.yml
  tags: slack

- name: Copy Karabiner config
  when: ansible_distribution in ["MacOSX"]
  copy:
    src: karabiner.json
    dest: "{{ home_dir }}/.config/karabiner/"
  tags: karabiner

- name: Copy fish config
  copy:
    src: fish
    dest: "{{ home_dir }}/.config"
  tags: fish

- import_tasks: repos.yml
  tags: repos
