---
- name: Install direnv
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: direnv
    state: latest
  tags: direnv

- name: Install StyLua
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: stylua
    state: latest
  tags: stylua

- name: Install Selene
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: selene
    state: latest
  tags: selene

- name: Copy Karabiner config
  when: ansible_distribution in ["MacOSX"]
  copy:
    src: karabiner.json
    dest: "{{ home_dir }}/.config/karabiner/"
  tags: karabiner

- name: Copy fish config
  copy:
    src: fish
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: fish
