---
- import_tasks: packages.yml
  tags: packages
- import_tasks: slack.yml
  tags: slack

- name: Install direnv
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: direnv
    state: latest
  tags: direnv

- name: Install direnv (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - direnv
    state: latest
  become: true
  tags: direnv

- name: Copy Karabiner config
  when: ansible_distribution in ["MacOSX"]
  copy:
    src: karabiner.json
    dest: "{{ home_dir }}/.config/karabiner/"
  tags: karabiner

- name: Copy fish config
  copy:
    src: fish
    dest: "{{ home_dir }}/.config"
  tags: fish

- import_tasks: repos.yml
  tags: repos
