---
- import_tasks: packages.yml
  tags: packages
- import_tasks: slack.yml
  tags: slack

- name: Copy fish config
  copy:
    src: fish
    dest: "{{ home_dir }}/.config"
  tags: fish

- import_tasks: repos-setup.yml
  tags: repos
