---
- name: Install pnpm node.js package globally.
  community.general.npm:
    name: pnpm
    global: true
  become: true

- name: Install direnv (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: direnv
    state: latest

- name: Install direnv (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - direnv
    state: latest
  become: true

- name: Install podman (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - podman
    state: latest
  become: true

- name: Install podman (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: podman
    state: latest

- name: Install OpenJDK 8 (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - openjdk-8-jdk
    state: latest
  become: true

- name: Install OpenJDK 11 (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - openjdk-11-jdk
    state: latest
  become: true

- name: Install OpenJDK 17 (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jdk
    state: latest
  become: true

- name: Install OpenJDK 8 (macOS based)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: openjdk@8
    state: latest

- name: Install OpenJDK 11 (macOS based)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: openjdk@11
    state: latest

- name: Install OpenJDK 17 (macOS based)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: openjdk@17
    state: latest

- name: Return brew prefix to registered var
  when: ansible_distribution in ["MacOSX"]
  ansible.builtin.command: brew --prefix
  register: development_workstations_brew_prefix

- name: Link OpenJDK 8 (macOS based)
  when: ansible_distribution in ["MacOSX"]
  ansible.builtin.file:
    src: "{{ development_workstations_brew_prefix.stdout }}/opt/openjdk@8/libexec/openjdk.jdk"
    dest: /Library/Java/JavaVirtualMachines/openjdk-8.jdk
    state: link
  become: true
