---
- hosts: all
  become: true

  tasks:

  - name: install updates (Debian based)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: install core packages
    package:
      name:
        - htop
        - exa
        - tmux
        - vim
        - zsh
      state: latest
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- hosts: workstation
  become: true

  tasks:

  - name: install workstation packages
    package:
      name:
        - fonts-open-sans
        - fonts-roboto-slab
      state: latest
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
