---
- hosts: all
  become: true

  tasks:

  - name: install updates (Debian based)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: install core packages
    tags: always
    package:
      name:
        - htop
        - exa
        - tmux
        - vim
        - zsh
      state: latest
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: copy gitconfig
    tags: always
    copy:
      src: .gitconfig
      dest: /home/brian/.gitconfig
      owner: brian
      group: brian
      mode: 0664

- hosts: workstation
  become: true

  tasks:

  - name: install workstation packages
    tags: workstation
    package:
      name:
        - fonts-open-sans
        - fonts-roboto-slab
      state: latest
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
