---
- hosts: all
  become: true
  tasks:

  - name: Install updates (Debian based)
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install core packages
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    apt:
      pkg:
        - htop
        - tmux
        - vim
        - zsh
      state: latest

  - name: Install lsd
    apt:
      deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb

  - name: Install starship
    unarchive:
      src: https://github.com/starship/starship/releases/download/v0.52.1/starship-x86_64-unknown-linux-gnu.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Copy git config
    copy:
      src: .gitconfig
      dest: /home/brian/.gitconfig
      owner: brian
      group: brian
      mode: 0664

  - name: Copy tmux config
    copy:
      src: .tmux.conf
      dest: /home/brian/.tmux.conf
      owner: brian
      group: brian
      mode: 0664

  - name: Copy vim config
    copy:
      src: .vimrc
      dest: /home/brian/.vimrc
      owner: brian
      group: brian
      mode: 0664

- hosts: workstations
  become: true
  tasks:

  - name: install workstation packages
    package:
      name:
        - unzip
        - fonts-open-sans
        - fonts-roboto-slab
      state: latest
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: Create fonts directory
    file:
      path: /home/brian/.local/share/fonts
      owner: brian
      group: brian
      state: directory

  - name: install Fira Code nerd fonts
    unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
      dest: /home/brian/.local/share/fonts
      remote_src: yes

  - name: install alacritty dependencies
    package:
      name:
        - cmake
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev
        - python3
        - cargo
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: install alacritty
    command: cargo install alacritty
    become_user: brian

  - name: Link alacritty binary
    file:
      src: /home/brian/.cargo/bin/alacritty
      dest: /usr/local/bin/alacritty
      owner: brian
      group: brian
      state: link

  - name: Create alacritty directory
    file:
      path: /home/brian/.config/alacritty
      owner: brian
      group: brian
      state: directory

  - name: copy alacritty config
    copy:
      src: alacritty.yml
      dest: /home/brian/.config/alacritty/alacritty.yml
      owner: brian
      group: brian
      mode: 0664

  - name: copy alacritty desktop file
    copy:
      src: Alacritty.desktop
      dest: /home/brian/.local/share/applications/Alacritty.desktop
      owner: brian
      group: brian
      mode: 0664

  - name: copy alacritty icon
    copy:
      src: alacritty-term.svg
      dest: /usr/share/pixmaps/Alacritty.svg

  - name: install alacritty terminfo
    command: tic -xe alacritty,alacritty-direct /home/brian/dev/ansible/files/alacritty.info

