---
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - bold
    selectedLineBgColor:
      - black

git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "P"
    command: "git push --force-with-lease -u origin {{.CheckedOutBranch.Name}}"
    context: "global"
    loadingText: "Pushing changes using force-with-lease"

startuppopupversion: 1
