---
gui:
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - yellow

git:
  paging:
    colorArg: always
    pager: delta --paging=never

startuppopupversion: 1
