window:
  padding:
    x: 3
    y: 3

  decorations: none

  startup_mode: Maximized

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 14

  # The normal (roman) font face to use.
  normal:
    family: FiraCode Nerd Font 
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3

selection:
  save_to_clipboard: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
shell:
  program: zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  - { key: Back,        mods: Super,                  chars: "\x15"          } # delete word/line
  - { key: Left,        mods: Alt,                    chars: "\x1bb"         } # one word left
  - { key: Right,       mods: Alt,                    chars: "\x1bf"         } # one word right
  - { key: V,           mods: Control,                action: Paste          }

 # tmux shortcuts

  - { key: Backslash,   mods: Control,                chars: "\x1c"          } # CTRL+\ required for Mac OS X
  - { key: T,           mods: Control,                chars: "\x1c\x63"      } # New window in tmux
  - { key: W,           mods: Control,                chars: "\x1c\x78"      } # Close pane in tmux
  # Move to panel x.
  - { key: Key1,        mods: Control,                chars: "\x1c\x31" }
  - { key: Key2,        mods: Control,                chars: "\x1c\x32" }
  - { key: Key3,        mods: Control,                chars: "\x1c\x33" }
  - { key: Key4,        mods: Control,                chars: "\x1c\x34" }
  - { key: Key5,        mods: Control,                chars: "\x1c\x35" }
  - { key: Key6,        mods: Control,                chars: "\x1c\x36" }
  # Tab around tmux windows
  - { key: Tab,         mods: Control,                chars: "\x1c\x6e" }
  - { key: Tab,         mods: Control|Shift,          chars: "\x1c\x70" }

