require("brian.plugins.gitsigns")
require("brian.plugins.lsp_signature")
require("brian.plugins.indent-blankline")
require("brian.plugins.lualine")
require("brian.plugins.nvim-autopairs")
require("brian.plugins.luasnip")
require("brian.plugins.rose-pine")
