local lspConfig = require("lspconfig")
local lspInstaller = require("nvim-lsp-installer")
local defaultConfig = require("brian.lsp.config-default")
local eslintConfig = require("brian.lsp.config-eslint")
local luaConfig = require("brian.lsp.config-lua")
local noFormatConfig = require("brian.lsp.config-noformat")
local typescriptConfig = require("brian.lsp.config-typescript")

lspInstaller.setup({ automatic_installation = true })

lspConfig.ansiblels.setup(defaultConfig)
lspConfig.cssls.setup(defaultConfig)
lspConfig.dockerls.setup(defaultConfig)
lspConfig.eslint.setup(eslintConfig)
lspConfig.gradle_ls.setup(defaultConfig)
lspConfig.html.setup(noFormatConfig)
lspConfig.jdtls.setup(defaultConfig)
lspConfig.jsonls.setup(noFormatConfig)
lspConfig.kotlin_language_server.setup(defaultConfig)
lspConfig.sumneko_lua.setup(luaConfig)
lspConfig.terraformls.setup(defaultConfig)
require("typescript").setup(typescriptConfig)
