gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - yellow

git:
  paging:
    colorArg: always
    pager: delta --paging=never

startuppopupversion: 1
