---
- name: Install the gedit package from flathub for current user
  community.general.flatpak:
    name: com.dropbox.Client
    method: user
  notify:
    - Restart Dropbox

- name: Copy systemd service file to server
  ansible.builtin.copy:
    src: dropbox.service
    dest: ~/.config/systemd/user/
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0664
  notify:
    - Restart Dropbox
