---
- name: Install packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - ubuntu-restricted-extras
      - wireguard
    state: latest
  become: true
