---
- name: Install digiKam flatpak
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.kde.digikam
    method: user

- name: Install darktable flatpak
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.darktable.Darktable
    method: user

- name: Install packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - ubuntu-restricted-extras
      - wireguard
    state: latest
  become: true
