---
- name: Install terraform (Pop!_OS)
  when: ansible_distribution in ["Pop!_OS"]
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_linux_amd64.zip
    dest: "{{ home_dir }}/.local/bin"
    remote_src: true
