---
- name: Install terraform (Pop!_OS)
  when: ansible_distribution in ["Pop!_OS"]
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
  tags: terraform
