---
- name: Install terraform (Pop!_OS)
  when: ansible_distribution in ["Pop!_OS"]
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.3.1/terraform_1.3.1_linux_amd64.zip
    dest: "{{ home_dir }}/.local/bin"
    remote_src: true
