---
- name: Install bat (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat_0.22.1_amd64.deb
  become: true

- name: Install bat (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: bat
    state: latest

- name: Copy bat config
  ansible.builtin.copy:
    src: bat
    dest: "{{ home_dir }}/.config"
    mode: 0775
