- name: Install bat
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.18.0/bat_0.18.0_amd64.deb
  tags: bat

- name: Copy bat config
  copy:
    src: bat
    dest: /home/brian/.config
    owner: brian
    group: brian
  tags: bat

