- name: Install bat (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.18.2/bat_0.18.2_amd64.deb
  tags: bat

- name: Install bat (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: bat
    state: latest
  tags: bat

- name: Copy bat config
  copy:
    src: bat
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: bat
