---
- name: Install bat (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.19.0/bat_0.19.0_amd64.deb
  become: true

- name: Install bat (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: bat
    state: latest

- name: Copy bat config
  copy:
    src: bat
    dest: "{{ home_dir }}/.config"
