- name: Install bottom
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/ClementTsang/bottom/releases/download/0.6.0/bottom_0.6.0_amd64.deb
  tags: bottom

- name: Copy bottom config
  copy:
    src: bottom
    dest: /home/brian/.config
    owner: brian
    group: brian
  tags: bottom

