---
- name: Install bottom (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/ClementTsang/bottom/releases/download/0.7.0/bottom_x86_64-unknown-linux-gnu.deb
  become: true

- name: Install bottom (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: bottom
    state: latest

- name: Copy bottom config
  ansible.builtin.copy:
    src: bottom
    dest: "{{ home_dir }}/.config"
    mode: 0775
