---
- name: Install bottom (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom_0.9.6_amd64.deb
  become: true

- name: Install bottom (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: bottom
    state: latest

- name: Copy bottom config
  ansible.builtin.copy:
    src: bottom
    dest: "{{ home_dir }}/.config"
    mode: 0775
