---
- name: Install delta (Debian)
  when: ansible_distribution in ["Debian"]
  apt:
    # Install musl due to https://github.com/dandavison/delta/issues/504
    deb: https://github.com/dandavison/delta/releases/download/0.11.3/git-delta-musl_0.11.3_amd64.deb
  tags: delta

- name: Install delta (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/dandavison/delta/releases/download/0.11.3/git-delta_0.11.3_amd64.deb
  tags: delta

- name: Install delta (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name:
      - git-delta
      - less
    state: latest
  tags: delta
