- name: Install delta (Debian)
  when: ansible_distribution in ["Debian"]
  apt:
    # Install musl due to https://github.com/dandavison/delta/issues/504
    deb: https://github.com/dandavison/delta/releases/download/0.7.1/git-delta-musl_0.7.1_amd64.deb
  tags: delta

- name: Install delta (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/dandavison/delta/releases/download/0.7.1/git-delta_0.7.1_amd64.deb
  tags: delta

