---
- name: Install Ansible task required packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - unzip
    state: latest
  become: true

- name: Create local bin directory (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  file:
    path: "{{ home_dir }}/.local/bin"
    state: directory
