---
- name: Install dust (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.unarchive:
    src: https://github.com/bootandy/dust/releases/download/v0.8.6/dust-v0.8.6-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ home_dir }}/.local/bin"
    remote_src: true
    extra_opts:
      # The dust zip contains a directory with the executable and some md files
      # We want to strip the directory and only take the executable
      - "--strip-components=1"
      - "dust-v0.8.6-x86_64-unknown-linux-gnu/dust"

- name: Install dust (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: dust
    state: latest
