- name: Install fd (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
    - fd-find
  tags: fd

- name: Create a symbolic link to fdfind
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    owner: root
    group: root
    state: link
  tags: fd

- name: Install fd (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: fd
    state: latest
  tags: fd
