---
- name: Install fd (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - fd-find
  become: true

- name: Create a symbolic link to fdfind
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: "{{ home_dir }}/.local/bin/fd"
    state: link

- name: Install fd (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: fd
    state: latest
