---
- name: Add the fish repository Apt signing key (Debian)
  when: ansible_distribution in ["Debian"]
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key
    dest: /usr/share/keyrings/shells_fish
    force: true
  become: true

- name: Dearmor the key (Debian)
  when: ansible_distribution in ["Debian"]
  ansible.builtin.command:
    argv:
      - gpg
      - --dearmor
      - --yes
      - /usr/share/keyrings/shells_fish
  become: true

- name: Remove armoured key (Debian)
  when: ansible_distribution in ["Debian"]
  ansible.builtin.file:
    path: /usr/share/keyrings/shells_fish
    state: absent
  become: true

- name: Add fish repository (Debian)
  when: ansible_distribution in ["Debian"]
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/shells_fish.gpg] http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /
    state: present
  become: true

- name: Add fish repository from PPA and install its signing key (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  become: true

- name: Install fish packages (Ubuntu based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    update_cache: true
    pkg:
      - fish
    state: latest
  become: true

- name: Install fish packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: fish
    state: latest

- name: Set fish as default shell
  user:
    name: "{{ user_name }}"
    shell: "{{ fish_location }}"
  become: true

- name: Copy fish config
  copy:
    src: fish
    dest: "{{ home_dir }}/.config"

- name: Install bass step 1
  get_url:
    url: https://raw.githubusercontent.com/edc/bass/master/functions/__bass.py
    dest: "{{ home_dir }}/.config/fish/functions/"

- name: Install bass step 2
  get_url:
    url: https://raw.githubusercontent.com/edc/bass/master/functions/bass.fish
    dest: "{{ home_dir }}/.config/fish/functions/"
