- name: Add the fish repository Apt signing key (Debian)
  when: ansible_distribution in ["Debian"]
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/shells:fish/Debian_10/Release.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/shells_fish.gpg
  tags: fish

- name: Add fish repository and install its signing key (Debian)
  when: ansible_distribution in ["Debian"]
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish/Debian_10/ /
    state: present
  tags: fish

- name: Add fish repository from PPA and install its signing key (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  tags: fish

- name: Install fish packages (Ubuntu based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    update_cache: yes
    pkg:
      - fish 
    state: latest
  tags: fish

- name: Set fish as default shell
  user:
    name: brian
    shell: /usr/bin/fish
  tags: fish

- name: Create fish config directory
  file:
    path: /home/brian/.config/fish
    owner: brian
    group: brian
    state: directory
  tags: fish

- name: Copy fish config
  copy:
    src: config.fish
    dest: /home/brian/.config/fish/config.fish
    owner: brian
  tags: fish

- name: Copy fish functions
  copy:
    src: functions
    dest: /home/brian/.config/fish
    owner: brian
  tags: fish

