- name: Install fzf (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  unarchive:
    src: https://github.com/junegunn/fzf/releases/download/0.27.3/fzf-0.27.3-linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags: fzf

- name: Install fzf (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: fzf
    state: latest
  tags: fzf

- name: Install fzf fish keybindings
  get_url:
    url: https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.fish
    dest: "{{ home_dir }}/.config/fish/functions/fzf_key_bindings.fish"
    owner: "{{ user_name }}"
  tags: fzf
