- name: Install git (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - git
    state: latest
  tags: git
 
- name: Copy git config
  copy:
    src: git
    dest: /home/brian/.config
    owner: brian
    group: brian
    mode: 0664
  tags: git

