- name: Install git (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - git
    state: latest
  tags: git
 
- name: Install git (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: git
    state: latest
  tags: git

- name: Copy git config
  copy:
    src: git
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: git

