- name: Install lazygit
  unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/download/v0.28.1/lazygit_0.28.1_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags: lazygit

- name: Copy lazygit config
  copy:
    src: lazygit
    dest: /home/brian/.config
    owner: brian
    group: brian
  tags: lazygit

