---
- name: Install LSDeluxe (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb
  become: true

- name: Install LSDeluxe (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: lsd
    state: latest

- name: Copy lsd config
  ansible.builtin.copy:
    src: lsd
    dest: "{{ home_dir }}/.config"
    mode: 0775
