---
- name: Install LSDeluxe (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.21.0/lsd_0.21.0_amd64.deb
  become: true

- name: Install LSDeluxe (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: lsd
    state: latest

- name: Copy lsd config
  copy:
    src: lsd
    dest: "{{ home_dir }}/.config"
