- name: Install LSDeluxe
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb
  tags: lsd

- name: Copy lsd config
  copy:
    src: lsd 
    dest: /home/brian/.config
    owner: brian
    group: brian
  tags: lsd

