- import_tasks: packages.yml
- import_tasks: git.yml
- import_tasks: lsd.yml
- import_tasks: bat.yml
- import_tasks: lazygit.yml
- import_tasks: fish.yml
- import_tasks: starship.yml
- import_tasks: delta.yml
- import_tasks: aliases.yml
- import_tasks: zoxide.yml
- import_tasks: bottom.yml
- import_tasks: neovim.yml
- import_tasks: fzf.yml

