- name: Install core packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - htop
      - tmux
      - vim
    state: latest
  tags: packages

- import_tasks: git.yml

- name: Copy tmux config
  copy:
    src: .tmux.conf
    dest: /home/brian/.tmux.conf
    owner: brian
    group: brian
    mode: 0664
  tags: tmux

- name: Copy vim config
  copy:
    src: .vimrc
    dest: /home/brian/.vimrc
    owner: brian
    group: brian
    mode: 0664
  tags: vim

- name: Install LSDeluxe
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb
  tags: lsd

- name: Create lsd config directory
  file:
    path: /home/brian/.config/lsd
    owner: brian
    group: brian
    state: directory
  tags: lsd

- name: Copy lsd config
  copy:
    src: lsd-config.yaml 
    dest: /home/brian/.config/lsd/config.yaml
    owner: brian
    group: brian
    mode: 0664
  tags: lsd

- name: Install delta (Debian)
  when: ansible_distribution in ["Debian"]
  apt:
    # Install musl due to https://github.com/dandavison/delta/issues/504
    deb: https://github.com/dandavison/delta/releases/download/0.7.1/git-delta-musl_0.7.1_amd64.deb
  tags: delta

- name: Install delta (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/dandavison/delta/releases/download/0.7.1/git-delta_0.7.1_amd64.deb
  tags: delta

- name: Install bat
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.18.0/bat_0.18.0_amd64.deb
  tags: bat

- name: Create bat config directory
  file:
    path: /home/brian/.config/bat
    owner: brian
    group: brian
    state: directory
  tags: bat

- name: Copy bat config
  copy:
    src: bat-config.conf
    dest: /home/brian/.config/bat/config
    owner: brian
    group: brian
    mode: 0664
  tags: bat

- name: Install zoxide
  get_url:
    url: https://github.com/ajeetdsouza/zoxide/releases/download/v0.6.0/zoxide-x86_64-unknown-linux-gnu
    dest: /usr/local/bin/zoxide
    mode: 0755
  tags: zoxide

- name: Install Starship
  unarchive:
    src: https://github.com/starship/starship/releases/download/v0.52.1/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags: starship

- name: Copy starship config
  copy:
    src: starship.toml
    dest: /home/brian/.config/starship.toml
    owner: brian
    group: brian
    mode: 0664
  tags: starship

- name: Install lazygit
  unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/download/v0.28.1/lazygit_0.28.1_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags: lazygit

- name: Create lazygit config directory
  file:
    path: /home/brian/.config/jesseduffield/lazygit
    owner: brian
    group: brian
    state: directory
  tags: lazygit

- name: Copy lazygit config
  copy:
    src: lazygit-config.yml
    dest: /home/brian/.config/jesseduffield/lazygit/config.yml
    owner: brian
    group: brian
    mode: 0664
  tags: lazygit

- name: Add the fish repository Apt signing key (Debian)
  when: ansible_distribution in ["Debian"]
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/shells:fish/Debian_10/Release.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/shells_fish.gpg
  tags: fish

- name: Add fish repository and install its signing key (Debian)
  when: ansible_distribution in ["Debian"]
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish/Debian_10/ /
    state: present
  tags: fish

- name: Add fish repository from PPA and install its signing key (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  tags: fish

- name: Install fish packages (Ubuntu based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    update_cache: yes
    pkg:
      - fish 
    state: latest
  tags: fish

- name: Set fish as default shell
  user:
    name: brian
    shell: /usr/bin/fish
  tags: fish

- name: Create fish config directory
  file:
    path: /home/brian/.config/fish
    owner: brian
    group: brian
    state: directory
  tags: fish

- name: Copy fish config
  copy:
    src: config.fish
    dest: /home/brian/.config/fish/config.fish
    owner: brian
    group: brian
    mode: 0664
  tags: fish

- name: Copy aliases config
  copy:
    src: aliases
    dest: /home/brian/.config/aliases
    owner: brian
    group: brian
    mode: 0664
  tags: aliases

