---
- name: Update repo cache (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  changed_when: false
  apt:
    update_cache: true
  tags: always

- name: Update repo cache (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  changed_when: false
  community.general.homebrew:
    update_homebrew: true
  tags: always

- import_tasks: node.yml
- import_tasks: packages.yml
- import_tasks: repos.yml
  tags: repos
- import_tasks: taskwarrior.yml
- import_tasks: fish.yml
- import_tasks: starship.yml
- import_tasks: tmux.yml
- import_tasks: neovim.yml
  tags: neovim
- import_tasks: git.yml
- import_tasks: lsd.yml
- import_tasks: bat.yml
  tags: bat
- import_tasks: lazygit.yml
- import_tasks: delta.yml
- import_tasks: bottom.yml
  tags: bottom
- import_tasks: fzf.yml
  tags: fzf
- import_tasks: ripgrep.yml
- import_tasks: fd.yml
- import_tasks: dust.yml
- import_tasks: tldr.yml
  tags: tldr
- import_tasks: selene.yml
- import_tasks: stylua.yml
  tags: stylua
