- name: Update repo cache (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  changed_when: false
  apt:
    update_cache: yes
  tags: always

- name: Update repo cache (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  changed_when: false
  community.general.homebrew:
    update_homebrew: yes
  tags: always

- import_tasks: packages.yml
- import_tasks: fish.yml
- import_tasks: starship.yml
- import_tasks: tmux.yml
- import_tasks: neovim.yml
- import_tasks: git.yml
- import_tasks: lsd.yml
- import_tasks: bat.yml
- import_tasks: lazygit.yml
- import_tasks: delta.yml
- import_tasks: bottom.yml
- import_tasks: fzf.yml
- import_tasks: ripgrep.yml
- import_tasks: fd.yml
- import_tasks: dust.yml
- import_tasks: tldr.yml

