---
- name: Update repo cache (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  changed_when: false
  apt:
    update_cache: true
  become: true
  tags: always

- name: Update repo cache (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  changed_when: false
  community.general.homebrew:
    update_homebrew: true
  tags: always

- import_tasks: node.yml
  tags: node
- import_tasks: packages.yml
  tags: packages
- import_tasks: fish.yml
  tags: fish
- import_tasks: starship.yml
  tags: starship
- import_tasks: tmux.yml
  tags: tmux
- import_tasks: neovim.yml
  tags: neovim
- import_tasks: lsd.yml
  tags: lsd
- import_tasks: bat.yml
  tags: bat
- import_tasks: delta.yml
  tags: delta
- import_tasks: bottom.yml
  tags: bottom
- import_tasks: fzf.yml
  tags: fzf
- import_tasks: ripgrep.yml
  tags: ripgrep
- import_tasks: fd.yml
  tags: fd
- import_tasks: dust.yml
  tags: dust
- import_tasks: tldr.yml
  tags: tldr
