---
- name: Add neovim PPA repository and install its signing key (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  become: true

- name: Install neovim (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - neovim
    state: present

- name: Install neovim packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: neovim
    state: latest

- name: Delete current neovim config
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/nvim"
    state: absent

- name: Copy neovim config
  copy:
    src: nvim
    dest: "{{ home_dir }}/.config"

- name: Git checkout of packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
