- name: Create neovim config directory
  file:
    path: /home/brian/.config/nvim
    owner: brian
    group: brian
    state: directory
  tags: neovim

- name: Copy neovim config
  copy:
    src: init.vim
    dest: /home/brian/.config/nvim/init.vim
    owner: brian
    group: brian
    mode: 0644
  tags: neovim

- name: Create neovim autoload directory
  file:
    path: /home/brian/.local/share/nvim/site/autoload
    owner: brian
    group: brian
    state: directory
  tags: neovim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/brian/.local/share/nvim/site/autoload/plug.vim
    mode: 0644
  tags: neovim

