- name: Install neovim (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - neovim
    state: latest
  tags: neovim

- name: Install neovim packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: neovim
    state: latest
  tags: neovim

- name: Copy neovim config
  copy:
    src: nvim
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: neovim

- name: Create neovim autoload directory
  file:
    path: "{{ home_dir }}/.local/share/nvim/site/autoload"
    owner: "{{ user_name }}"
    state: directory
  tags: neovim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home_dir }}/.local/share/nvim/site/autoload/plug.vim"
  tags: neovim
