---
- name: Add neovim PPA repository and install its signing key (Ubuntu based)
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  tags: neovim

- name: Install neovim (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - neovim
    state: latest
  tags: neovim

- name: Install neovim packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: neovim
    state: latest
  tags: neovim

- name: Delete current neovim config
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/nvim"
    state: absent
  tags: neovim

- name: Copy neovim config
  copy:
    src: nvim
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: neovim

- name: Git checkout of packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags: neovim

- name: Recursively change ownership of packer directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.local/share/nvim/site/pack/packer/"
    state: directory
    recurse: true
    owner: "{{ user_name }}"
  tags: neovim
