---
- name: Install neovim (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.8.1/nvim-linux64.deb
  become: true

- name: Install neovim packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: neovim
    state: latest

- name: Delete current neovim config
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/nvim"
    state: absent

- name: Copy neovim config
  ansible.builtin.copy:
    src: nvim
    dest: "{{ home_dir }}/.config"
    mode: 0775

- name: Git checkout of packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
