---
- name: Install neovim (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage
    dest: "{{ home_dir }}/.local/bin/nvim"
    mode: 0755

- name: Install neovim packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: neovim
    state: latest

- name: Delete current neovim config
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/nvim"
    state: absent

- name: Copy neovim config
  ansible.builtin.copy:
    src: nvim
    dest: "{{ home_dir }}/.config"
    mode: 0775
