---
- name: Install Ansible task required packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - unzip
      - python3-pip
    state: latest
  tags: packages

- name: Install yamllint python package
  pip:
    name:
      - yamllint
      - ansible-lint
  tags: packages

- name: Install "prettierd" node.js package globally.
  community.general.npm:
    name: "@fsouza/prettierd"
    global: true
  tags: packages
