---
- name: Install ripgrep (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
  become: true

- name: Install ripgrep (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: ripgrep
    state: latest
