- name: Install ripgrep (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
  tags: ripgrep

- name: Install ripgrep (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: ripgrep
    state: latest
  tags: ripgrep

