- name: Install Starship
  unarchive:
    src: https://github.com/starship/starship/releases/download/v0.52.1/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags: starship

- name: Copy starship config
  copy:
    src: starship.toml
    dest: /home/brian/.config/starship.toml
    owner: brian
    group: brian
    mode: 0664
  tags: starship

