---
- name: Install StyLua (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: stylua
    state: latest

- name: Install StyLua (Pop!_OS)
  when: ansible_distribution in ["Pop!_OS"]
  unarchive:
    src: https://github.com/JohnnyMorganz/StyLua/releases/download/v0.12.1/stylua-0.12.1-linux.zip
    dest: "{{ home_dir }}/.local/bin/"
    remote_src: true
    mode: o+x
