---
- name: Install Taskwarrior packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - taskwarrior
    state: latest

- name: Install Taskwarrior packages (MacOSX based)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: task
    state: latest

- name: Copy Taskwarrior config template
  ansible.builtin.template:
    src: .taskrc
    dest: "{{ home_dir }}"
