- name: Install tldr (Linux)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  get_url:
    url: https://github.com/dbrgn/tealdeer/releases/download/v1.4.1/tldr-linux-x86_64-musl
    dest: /usr/local/bin/tldr
    mode: 0755
  tags: tldr

- name: Install tldr (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: tealdeer
    state: latest
  tags: tldr

- name: Install tldr fish completions
  get_url:
    url: https://github.com/dbrgn/tealdeer/releases/download/v1.4.1/completions_fish
    dest: "{{ home_dir }}/.config/fish/completions/tldr.fish"
    mode: 0644
    owner: "{{ user_name }}"
  tags: tldr

