---
- name: Install tldr (Linux)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.get_url:
    url: https://github.com/dbrgn/tealdeer/releases/download/v1.6.0/tealdeer-linux-x86_64-musl
    dest: "{{ home_dir }}/.local/bin/tldr"
    mode: 0755

- name: Install tldr (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: tealdeer
    state: latest

- name: Install tldr fish completions
  ansible.builtin.get_url:
    url: https://github.com/dbrgn/tealdeer/releases/download/v1.6.0/completions_fish
    dest: "{{ home_dir }}/.config/fish/completions/tldr.fish"
    mode: 0664

- name: Update tldr cache
  ansible.builtin.command:
    argv:
      - tldr
      - --update
  register: update_result
  changed_when: update_result.stdout != ""
