---
- name: Install tmux (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - tmux
    state: latest
  become: true

- name: Install tmux packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: tmux
    state: latest

- name: Copy tmux config
  copy:
    src: tmux.conf
    # ~/.config/tmux/tmux.conf support was added to tmux 3.1a
    # but Debian hasn't released it yet
    dest: "{{ home_dir }}/.tmux.conf"

- name: Git checkout of tpm
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ home_dir }}/.tmux/plugins/tpm"
