- name: Install zoxide (Linux)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  unarchive:
    src: https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      # The zip contains a directory with the executable and some md files
      # We want to strip the directory and take only the executable
      - "--strip-components=1"
      - "zoxide-x86_64-unknown-linux-musl/zoxide"
  tags: zoxide

- name: Install zoxide (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: zoxide
    state: latest
  tags: zoxide

