window:
  padding:
    x: 3
    y: 3

  decorations: none

  startup_mode: Maximized

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 14

  # The normal (roman) font face to use.
  normal:
    family: FiraCode Nerd Font 
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3

selection:
  save_to_clipboard: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
shell:
  program: fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
# tmux shortcuts

  # CTRL+\ for Mac OS X
  - { key: Backslash,   mods: Control,                chars: "\x1c"     }
  # Alt-C for Mac OS X https://github.com/alacritty/alacritty/issues/62
  - { key: C,           mods: Alt,                    chars: "\x1bc"    }
  # Move to window n
  - { key: Key1, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 1"] }}
  - { key: Key2, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 2"] }}
  - { key: Key3, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 3"] }}
  - { key: Key4, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 4"] }}
  - { key: Key5, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 5"] }}
  - { key: Key6, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 6"] }}
  - { key: Key7, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 7"] }}
  - { key: Key8, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 8"] }}
  - { key: Key9, mods: Control, command: { program: "fish", args: ["-c", "new-tmux-window 9"] }}
  # Move to pane n
  - { key: Key1,        mods: Alt,                chars: "\x1c\x1b\x31" }
  - { key: Key2,        mods: Alt,                chars: "\x1c\x1b\x32" }
  - { key: Key3,        mods: Alt,                chars: "\x1c\x1b\x33" }
  - { key: Key4,        mods: Alt,                chars: "\x1c\x1b\x34" }
  - { key: Key5,        mods: Alt,                chars: "\x1c\x1b\x35" }
  - { key: Key6,        mods: Alt,                chars: "\x1c\x1b\x36" }
  - { key: Key7,        mods: Alt,                chars: "\x1c\x1b\x37" }
  - { key: Key8,        mods: Alt,                chars: "\x1c\x1b\x38" }
  - { key: Key9,        mods: Alt,                chars: "\x1c\x1b\x39" }

