- name: Install core packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - htop
      - tmux
      - vim
      - fish
    state: latest

- name: Copy git config
  copy:
    src: .gitconfig
    dest: /home/brian/.gitconfig
    owner: brian
    group: brian
    mode: 0664

- name: Create git config directory
  file:
    path: /home/brian/.config/git
    owner: brian
    group: brian
    state: directory

- name: Copy git message template config
  copy:
    src: git-message-template 
    dest: /home/brian/.config/git/message-template
    owner: brian
    group: brian
    mode: 0664

- name: Copy tmux config
  copy:
    src: .tmux.conf
    dest: /home/brian/.tmux.conf
    owner: brian
    group: brian
    mode: 0664

- name: Copy vim config
  copy:
    src: .vimrc
    dest: /home/brian/.vimrc
    owner: brian
    group: brian
    mode: 0664

- name: Install LSDeluxe
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb

- name: Install delta
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/dandavison/delta/releases/download/0.7.1/git-delta_0.7.1_amd64.deb

- name: Install bat
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.18.0/bat_0.18.0_amd64.deb

- name: Create bat config directory
  file:
    path: /home/brian/.config/bat
    owner: brian
    group: brian
    state: directory

- name: Copy bat config
  copy:
    src: bat-config.conf
    dest: /home/brian/.config/bat/config
    owner: brian
    group: brian
    mode: 0664

- name: Install zoxide
  get_url:
    url: https://github.com/ajeetdsouza/zoxide/releases/download/v0.6.0/zoxide-x86_64-unknown-linux-gnu
    dest: /usr/local/bin/zoxide
    mode: 0755

- name: Install Starship
  unarchive:
    src: https://github.com/starship/starship/releases/download/v0.52.1/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Copy starship config
  copy:
    src: starship.toml
    dest: /home/brian/.config/starship.toml
    owner: brian
    group: brian
    mode: 0664

- name: Install lazygit
  unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/download/v0.28.1/lazygit_0.28.1_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create lazygit config directory
  file:
    path: /home/brian/.config/jesseduffield/lazygit
    owner: brian
    group: brian
    state: directory

- name: Copy lazygit config
  copy:
    src: lazygit-config.yml
    dest: /home/brian/.config/jesseduffield/lazygit/config.yml
    owner: brian
    group: brian
    mode: 0664

- name: Set fish as default shell
  user:
    name: brian
    shell: /usr/bin/fish

- name: Copy fish config
  copy:
    src: config.fish
    dest: /home/brian/.config/fish/config.fish
    owner: brian
    group: brian
    mode: 0664

- name: Copy aliases config
  copy:
    src: aliases
    dest: /home/brian/.config/aliases
    owner: brian
    group: brian
    mode: 0664

