---
- name: Install alacritty dependencies (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
      - cargo
    state: latest
  tags: alacritty

- name: Install alacritty (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  command: cargo install alacritty
  become_user: brian
  tags: alacritty

- name: Install alacritty (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - alacritty
    state: latest
  tags: alacritty

- name: Link alacritty binary (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  file:
    src: /home/brian/.cargo/bin/alacritty
    dest: /usr/local/bin/alacritty
    owner: brian
    group: brian
    state: link
  tags: alacritty

- name: Copy alacritty config
  copy:
    src: alacritty
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: alacritty

- name: Copy alacritty desktop file (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  copy:
    src: Alacritty.desktop
    dest: /home/brian/.local/share/applications/Alacritty.desktop
    owner: brian
    group: brian
    mode: 0664
  tags: alacritty

- name: Copy alacritty icon (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  copy:
    src: alacritty-term.svg
    dest: /usr/share/pixmaps/Alacritty.svg
  tags: alacritty

- name: Install alacritty terminfo (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  command: tic -xe alacritty,alacritty-direct /home/brian/dev/ansible/roles/workstations/files/alacritty.info
  tags: alacritty
