---
- name: Create fonts directory (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.file:
    path: "{{ home_dir }}{{ fonts_directory }}"
    state: directory
    mode: 0755

- name: Create temporary font extraction directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_font_dir

- name: Download JetBrains Mono into temporary fonts directory
  ansible.builtin.unarchive:
    src: https://download-cdn.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    dest: "{{ temp_font_dir.path }}"
    remote_src: true

- name: Copy JetBrains Mono to fonts directory
  ansible.builtin.copy:
    src: "{{ temp_font_dir.path }}/fonts/variable/"
    dest: "{{ home_dir }}{{ fonts_directory }}"
    mode: 0644

- name: Install Symbols only nerd font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/NerdFontsSymbolsOnly.zip
    dest: "{{ home_dir }}{{ fonts_directory }}"
    remote_src: true

- name: Install font packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - fonts-noto
      - fonts-roboto-slab
    state: latest
  become: true

- name: Add fonts cask (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install font packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - font-noto-sans
      - font-roboto-slab
    state: latest
