---
- name: Install font packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - fonts-open-sans
      - fonts-roboto-slab
    state: latest
  tags: fonts

- name: Add fonts cask (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  tags: fonts

- name: Install font packages (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - font-open-sans
      - font-roboto-slab
      - font-fira-code-nerd-font
    state: latest
  tags: fonts

- name: Create fonts directory (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  file:
    path: /home/brian/.local/share/fonts
    owner: brian
    state: directory
  tags: fonts

- name: Install Fira Code nerd fonts
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: /home/brian/.local/share/fonts
    remote_src: yes
  tags: fonts
