---
- name: install playbook requirements
  package:
    name:
      - python3-psutil
  become: true

- name: Switch to workspace 1 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
    value: "['<Super>Home', '<Super>1']"

- name: Switch to workspace 2 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
    value: "['<Super>2']"

- name: Switch to workspace 3 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
    value: "['<Super>3']"

- name: Switch to workspace 4 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
    value: "['<Super>4']"

- name: Switch to workspace 5 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5"
    value: "['<Super>5']"

- name: Switch to workspace 6 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6"
    value: "['<Super>6']"

- name: Switch to workspace 7 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7"
    value: "['<Super>7']"

- name: Switch to workspace 8 shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8"
    value: "['<Super>8']"
