---
- name: Install kitty (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - kitty
    state: latest

- name: Create kitty directory (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  file:
    path: "{{ home_dir }}/.local/kitty"
    state: directory

- name: Install kitty (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  unarchive:
    src: https://github.com/kovidgoyal/kitty/releases/download/v0.25.2/kitty-0.25.2-x86_64.txz
    dest: "{{ home_dir }}/.local/kitty"
    remote_src: true

- name: Link kitty binary (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  file:
    src: "{{ home_dir }}/.local/kitty/bin/kitty"
    dest: "{{ home_dir }}/.local/bin/kitty"
    state: link

- name: Copy kitty icon (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  copy:
    src: "{{ home_dir }}/.local/kitty/share/applications/kitty.desktop"
    dest: "{{ home_dir }}/.local/share/applications"

- name: Change kitty icon file path (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.lineinfile:
    path: "{{ home_dir }}/.local/share/applications/kitty.desktop"
    regexp: "^Icon=kitty$"
    line: "Icon={{ home_dir }}/.local/kitty/share/icons/hicolor/256x256/apps/kitty.png"

- name: Install kitty-terminfo (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    pkg:
      - kitty-terminfo
    state: present
  become: true

- name: Copy kitty config
  copy:
    src: kitty
    dest: "{{ home_dir }}/.config"

- name: Link host specific config
  file:
    src: "{{ home_dir }}/.config/kitty/{{ inventory_hostname }}.conf"
    dest: "{{ home_dir }}/.config/kitty/host-config.conf"
    state: link
