---
- name: Install kitty (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - kitty
    state: latest
  tags: kitty

- name: Copy kitty config
  copy:
    src: kitty
    dest: "{{ home_dir }}/.config"
    owner: "{{ user_name }}"
  tags: kitty
