---
- name: Install lazygit (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.unarchive:
    src: https://github.com/jesseduffield/lazygit/releases/download/v0.37.0/lazygit_0.37.0_Linux_x86_64.tar.gz
    dest: "{{ home_dir }}/.local/bin"
    remote_src: true
    extra_opts:
      # The lazygit zip contains the executable and some md files. We want to
      # strip the md files and only take the executable
      - "lazygit"

- name: Install lazygit (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: jesseduffield/lazygit/lazygit
    state: latest

- name: Copy lazygit config
  ansible.builtin.copy:
    src: lazygit
    dest: "{{ lazygit_config_dir }}"
    mode: 0775
