---
- import_tasks: git.yml
  tags: git
- import_tasks: lazygit.yml
  tags: lazygit
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: kitty.yml
  tags: kitty
- import_tasks: node.yml
  tags: node
- import_tasks: packages.yml
  tags: packages
- import_tasks: karabiner.yml
  tags: karabiner
- import_tasks: gnome.yml
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  tags: gnome
