---
- import_tasks: git.yml
  tags: git
- import_tasks: lazygit.yml
  tags: lazygit
- import_tasks: selene.yml
  tags: selene
- import_tasks: stylua.yml
  tags: stylua
- import_tasks: taskwarrior.yml
  tags: taskwarrior
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: kitty.yml
  tags: kitty
- import_tasks: node.yml
  tags: node
- import_tasks: remmina.yml
  tags: remmina
- import_tasks: gnome.yml
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  tags: gnome
