---
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: kitty.yml
  tags: kitty
- import_tasks: remmina.yml
  tags: remmina
- import_tasks: gnome.yml
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  tags: gnome
