---
- import_tasks: git.yml
  tags: git
- import_tasks: lazygit.yml
  tags: lazygit
- import_tasks: fonts.yml
  tags: fonts
- import_tasks: kitty.yml
  tags: kitty
- import_tasks: node.yml
  tags: node
- import_tasks: packages.yml
  tags: packages
- import_tasks: audacious.yml
  tags: audacious
- import_tasks: remmina.yml
  tags: remmina
- import_tasks: flatseal.yml
  tags: flatseal
- import_tasks: steam.yml
  tags: steam
- import_tasks: hgl.yml
  tags: hgl
- import_tasks: vlc.yml
  tags: vlc
- import_tasks: karabiner.yml
  tags: karabiner
- import_tasks: gnome.yml
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  tags: gnome
