---
- name: Install chrome (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- name: Install chrome (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - google-chrome
    state: latest

- name: Install firefox (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - firefox
    state: latest

- name: Install lint python packages (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  pip:
    name:
      - yamllint
      - ansible-lint
      - proselint
    state: latest

- name: Install lint python packages (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name:
      - yamllint
      - ansible-lint
      - proselint

- name: Install "prettierd" node.js package globally.
  community.general.npm:
    name: "@fsouza/prettierd"
    global: true
    state: latest
  become: true

- name: Install write-good node.js package globally.
  community.general.npm:
    name: write-good
    global: true
    state: latest
  become: true

- name: Install markdownlint node.js package globally.
  community.general.npm:
    name: markdownlint-cli
    global: true
    state: latest
  become: true
