---
- name: Install chrome (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- name: Install chrome (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - google-chrome
    state: latest

- name: Install firefox (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - firefox
    state: latest

- name: Install virt-manager for virt-viewer (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.apt:
    pkg:
      - virt-manager
  become: true

- name: Install the Krita package from flathub
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.kde.krita
    method: user
