---
- name: Install Audacious (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.atheme.audacious
    method: user

- name: Install Flatseal (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    method: user

- name: Install Heroic Games Launcher (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: com.heroicgameslauncher.hgl
    method: user

- name: Install chrome (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: com.google.Chrome
    method: user

- name: Install chrome (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - google-chrome
    state: latest

- name: Install firefox (macOS)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew_cask:
    name:
      - firefox
    state: latest

- name: Install virt-viewer (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.virt_manager.virt-viewer
    method: user

- name: Install Remmina (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.remmina.Remmina
    method: user

- name: Install Krita (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.kde.krita
    method: user

- name: Install Steam (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: com.valvesoftware.Steam
    method: user

- name: Install VLC (Debian based)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  community.general.flatpak:
    name: org.videolan.VLC
    method: user
