---
- name: Git checkout of my-data repo
  ansible.builtin.git:
    repo: git@github.com:briandipalma/my-data.git
    accept_hostkey: true
    dest: "{{ home_dir }}/dev/my-data"

- name: Git checkout of ansible repo
  ansible.builtin.git:
    repo: git@github.com:briandipalma/ansible.git
    accept_hostkey: true
    dest: "{{ home_dir }}/dev/ansible"
