---
- name: Install StyLua (MacOSX)
  when: ansible_distribution in ["MacOSX"]
  community.general.homebrew:
    name: stylua
    state: latest

- name: Install StyLua (Debian)
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
  ansible.builtin.unarchive:
    src: https://github.com/JohnnyMorganz/StyLua/releases/download/v0.15.3/stylua-linux-x86_64.zip
    dest: "{{ home_dir }}/.local/bin/"
    remote_src: true
    mode: 0755
